### ISSUE TITLE
Overload on 0.4 not on 0.3.1/0.2

### ISSUE THREAD

**Issue by Donzii** [fzwoch/obs-vaapi#17]
Hi,
im testing the plugin on my pc that i use as a console-system.
(xbox - steambox for only gaming on a 65" in 2k90 with MangoHud-fps-limiter, sometimes in 2k60/4k60 vSync on or MangoHud-fps-limiter)

i record my gameplays in relative high-fps. i came from windows with 120fps, on linux i get 90 without overloading.
why i cant record in 120, is another problem. is not relevant here, or is it?

vaapi v0.2 and 0.3.1 have perfect records, but 0.4 overloads. each new plugin-insert i check the settings and correct them.
records on 90, 78 or 60, it overloads. obs v 29.1.3 or the 30.0 beta, same.

maybe a problem with the old version of gstreamer?

here the logs. i hope it can help
i mean, its not a problem, i can use the 0.3.1, its only fyi ;o)

v0.2
[2023-10-07 22-18-44.txt](https://github.com/fzwoch/obs-vaapi/files/12840959/2023-10-07.22-18-44.txt)

v0.3.1
[2023-10-07 22-22-20.txt](https://github.com/fzwoch/obs-vaapi/files/12840960/2023-10-07.22-22-20.txt)

v0.4
[2023-10-07 22-24-46.txt](https://github.com/fzwoch/obs-vaapi/files/12840961/2023-10-07.22-24-46.txt)

my system-info
https://termbin.com/cona

**Comment by fzwoch** [comment]
0.4.0 uses vaapipostproc instead of vaposptroc, as they should not be mixed.

try va plugins instead og vaapi. vaapi is basically dead und superseeded by va.

actually 0.3.1 should only list encoders when you have vapostproc. however, the va plugins are not listed in the log.. which puzzles me a bit..

**Comment by Donzii** [comment]
did you mean, do not mix obs-gstreamer.so AND obs-vaapi.so in 1 installation?
/.config/obs-studio/plugins/obs-vaapi/bin/64bit/obs-vaapi.so
/.config/obs-studio/plugins/obs-gstreamer/bin/64bit/obs-gstreamer.so
ok, i will test each plugin alone, no problem :o)

which va plugins do you mean? its not a flatpak-obs, its LinuxMint 21.2 with OBS-PPA 29.1.3 and OBS-GitHub-beta

Quote:
"try va plugins instead og vaapi. vaapi is basically dead und superseeded by va."
I do not understand that now (mein englisch ist nicht ganz perfekt)

**Comment by fzwoch** [comment]
Your English is fine. obs-gstreamer and obs-vaapi can co-exists. But I discourage from using obs-gstreamer for encoding, it has a couple of issues.

Within GStreamer there are two different sets of vaapi encoder plugins. obs-vaapi should offer both types - legacy and the new ones. Legacy are in package `vaapi` and newer ones are in package `va`. Not sure how your linux distributions packages these.

Withing the OBS log you should see these:
```
info: [obs-vaapi] version: 0.4.0-3-g350b3de, gst-runtime: 1.22.6
info: [obs-vaapi] found vah265enc
info: [obs-vaapi] found vah264enc
info: [obs-vaapi] found vaapih264enc
info: [obs-vaapi] found vaapih265enc
```
`va...` means new
`vaapi...` means the old one (you are using)

There have been reports of some performance issues with the new ones as well. But I think it is important to test and report these upstream to GStreamer as the old ones will go away at some point.

But indeed I noticed that you will need GStreamer 1.22 for the new ones..

**Comment by Donzii** [comment]
ahh yes, Mint 21.2 has gstreamer 1.20.3 thats why i using the "legacy"

hope i can compile 1.22.x https://github.com/GStreamer/gstreamer myself without breaking anything :D

**Comment by fzwoch** [comment]
May be a tough one. As long as you found a way to make it work for you it is fine :)

Just keep an eye on the new ones when you have them available.

I will close this one as it is probably an issue with the legacy postproc and the older versions get away it as they use the new one - although it is not correct to use it.
