### ISSUE TITLE
what environment variables are needed?

### ISSUE THREAD

**Issue by Pearf1337** [fzwoch/obs-vaapi#20]
As of https://github.com/flathub/com.obsproject.Studio.Plugin.GStreamerVaapi/issues/17 i am trying to make work the "new" va encoder in the flatpak version. See linked issue.

Since the native obs studio with plugin ist working fine i am wondering what permissions or environment variables are needed? What are the files that obs has to access?

I tried `GST_PLUGIN_SYSTEM_PATH` but no luck so far.

**Comment by fzwoch** [comment]
I have no idea about Flatpak. But as I understand there is no such think. Flatpak ecosystem installs its own version of GStreamer runtime and plugins. So there is no such think as a variable to leak outside the container - that would certainly almost never work correctly.

It is more about the Flatpak runtime to have a recent GStreamer version with the plugins installed.
