### ISSUE TITLE
Getting a segfault form libpci

### ISSUE THREAD

**Issue by jnettlet** [fzwoch/obs-vaapi#21]
I believe you sscanf matching implementation in get_device_name and populate_devices is slightly incorrect. Your format specifier matches everything up to the - character which leaves the separator as part of the domain integer. If the domain is zero this is most likely irrelevant since -0 should be overlooked. However for my configuration this was making the domain -4 which is obviously invalid. Instead I have changed the code as following to get things up and working.

```
@@ -649,7 +649,7 @@ static void populate_devices(obs_property_t *prop)
                char device[1024] = {};
                int domain, bus, dev, fun;
 
-               sscanf(list[i]->d_name, "%*[^-]%x:%x:%x.%x%*s", &domain, &bus,
+               sscanf(list[i]->d_name, "%*[^-]-%x:%x:%x.%x%*s", &domain, &bus,
                       &dev, &fun);
```

**Comment by fzwoch** [comment]
Nice catch, thanks!

**Comment by jnettlet** [comment]
No problem. Thanks for the excellent plugin. Thanks for integrating the fix so quickly. I was actually planning on sending a pull request later.

Just one correct the function populate_devices() also needs this same fix.

Thanks,
Jon
________________________________

**Comment by fzwoch** [comment]
Ugh, didn't realize I had it twice because of the legacy encoders. Fixed!
