### ISSUE TITLE
VAAPI H.264 on Navi 22 results in bad output when output resolution different from 720p

### ISSUE THREAD

**Issue by physixcat** [fzwoch/obs-vaapi#23]
Selecting `VAAPI H.264 on Navi 22 [Radeon RX 6700/6700 XT/6750 XT/6800M/6850M XT]` as Video Encoder (with its default settings) and an output (scaled) resolution above OR below 1280x720 results in recordings looking like this

![mpv-shot0004](https://github.com/fzwoch/obs-vaapi/assets/32757992/a12bf2fa-3077-499a-8c1e-b9271a148bc3)

If I stay at 720p, I get normal output.
Selecting `VAAPI H.264 (Legacy)` encoder with default settings doesn't have this issue

I'm curious what the differences between the two are. Does the first implement a feature not supported on the 6700 XT? Wondering why it would behave like this when switching away from 720p

System info:
```
obs-studio 1:30.0.1-dmo1 (from deb-multimedia repo)
obs-vaapi 0.4.1
GStreamer 1.22.8
Mesa 23.3.1-4
Linux 6.5.0-4-amd64
Radeon RX 6700 XT
Debian Sid
```

**Comment by therealmate** [comment]
Could this be the same issue as https://gitlab.freedesktop.org/mesa/mesa/-/issues/10063?

**Comment by fzwoch** [comment]
Yeah looks very much like a stride issue like the mesa report. Seems like the GStreamer fix is the culprit. Unfortunately it seems this patch is not  back ported to the stable release.

**Comment by physixcat** [comment]
Damn, I guess I have to contact the Debian multimedia package managers then. Thank you

**Comment by physixcat** [comment]
You were right, the issue is fixed with the patch linked above. deb-multimedia maintainer pushed version `1:1.22.8-dmo2` of `gstreamer1.0-plugins-bad:amd64` and `libgstreamer-plugins-bad1.0-0:amd64` . Thank you!

**Comment by fzwoch** [comment]
Looks like
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/commit/099741e35f60499e69a3ba8d79dad9f242bf5a40

Found it's way into GStreamer 1.22.9
