### ISSUE TITLE
Limited and Full Color Range OBS setting not being passed to encoder.

### ISSUE THREAD

**Issue by RushingAlien** [fzwoch/obs-vaapi#27]
Hello, OBS has a pixel format setting for video in the advanced tab where we can choose between full range (0-255 for 8-bit yuv) or limited range (16-235) color range.

## Color Range setting
![gambar](https://github.com/fzwoch/obs-vaapi/assets/80886145/4a81316f-9b75-4bce-8f07-d0af2a35c21b)

## FFMPEG VAAPI result
Recording with this state with the ffmpeg vaapi encoders in OBS results in a video with full color range (Levels)

![gambar](https://github.com/fzwoch/obs-vaapi/assets/80886145/ca04a8d1-a745-4b76-b433-f08988cae41e)

## obs-vaapi result
However the obs-vaapi encoded ones are still encoding in `limited` while OBS is giving full range frames, causing bad color mapping when playbacked.

![gambar](https://github.com/fzwoch/obs-vaapi/assets/80886145/04350539-f33c-4663-80d7-802adb2e2724)

In this image, the top part is what the color should look like, the bottom part is what shows when obs-vaapi encoded video is play-backed.

![](https://private-user-images.githubusercontent.com/80886145/333807949-1dec04c7-cff8-4467-bda5-dbb9aa743d4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NTM0MzgsIm5iZiI6MTcxNjY1MzEzOCwicGF0aCI6Ii84MDg4NjE0NS8zMzM4MDc5NDktMWRlYzA0YzctY2ZmOC00NDY3LWJkYTUtZGJiOWFhNzQzZDRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDE2MDUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0ZjRmNDdjNmY1ZDY3Yzk5MTBjNjNkODRkOTE1ZDhkOTQ4NTBiMmZjZTAxMzY5N2NjYTkxYjcxY2I0MDNhOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5lSLjCvkx9oWi-vq7BKDngSgz6FsL2c3pHw5rHXEqLI)

## Additional Information
https://gstreamer.freedesktop.org/documentation/video/video-color.html

looks like this can be set via `GstVideoColorimetry`
>
> GstVideoColorRange
>
> Possible color range values. These constants are defined for 8 bit color values and can be scaled for other bit depths.
Members
> GST_VIDEO_COLOR_RANGE_UNKNOWN (0) – unknown range  
> GST_VIDEO_COLOR_RANGE_0_255 (1) – [0..255] for 8 bit components  
> GST_VIDEO_COLOR_RANGE_16_235 (2) –  [16..235] for 8 bit components. Chroma has [16..240] range.

**Comment by RushingAlien** [comment]
More information: when video is played with gstreamer the color looks accurate, but not if with ffmpeg. Maybe this is because gst looks at colorimetry data directly while ffmpeg relies on metadata?

**Comment by fzwoch** [comment]
I think this can be added. But note this is almost always not want you want.
