### ISSUE TITLE
Suggestion regarding options

### ISSUE THREAD

**Issue by GloriousEggroll** [fzwoch/obs-vaapi#3]
Since there currently are a lot of options it can be overwhelming for new users. Would it be viable maybe to add a dropdown with simple/advanced mode? simple mode maybe just presents device select, CBR mode with default bitrate and keyframe, (and or whatever other options you think would be useful in a simple to use mode), then advanced mode would show the full list of options. Not an issue, just a thought/suggestion on usability

**Comment by fzwoch** [comment]
Quite unlikely. There is no clear line to draw and people will request different things for simple mode.

But the main reason is that I don't want to maintain such code and make special handling for certain things. These options are currently automated to provide options from the GStreamer API and pass it through to OBS.

This way I don't need to update (almost) anything in this plugin when the new set of VAAPI encoder elements in GStreamer get released, or the GStreamer version gets updated on the host machine that change some options in the encoder.

**Comment by GloriousEggroll** [comment]
Ah I understand, that makes sense. I'll go ahead and close this then.
