### ISSUE TITLE
01f62dac9678302799a01761b732c523c7294bab breaks the plugin

### ISSUE THREAD

**Issue by GloriousEggroll** [fzwoch/obs-vaapi#4]
```
info: [ffmpeg muxer: 'adv_file_output'] Writing file '/home/tcrider/2022-09-06 13-38-00.mkv'...
error: [obs-vaapi] Internal data stream error.
```
start recording never creates the file,when you hit the stop recording button it hangs indefinitely. 

reverting prior to that commit resolves the issue

**Comment by Atemu** [comment]
Just a hunch but 01f62dac9678302799a01761b732c523c7294bab requires a new dependency, is it installed in your system?

**Comment by fzwoch** [comment]
That's right. That commit switches to `vapostproc` which is part of the newer VA plugin. Probably with the next release of GStreamer the encoder will switch to this new version as well. Currently this plugin is part of the `-bad` set of plugins of GStreamer. The old `vaapipostproc` caused to many issues and errors with various color formats that `vapostproc` works just quite well with.

**Comment by GloriousEggroll** [comment]
$ rpm -qa | grep gstreamer | grep bad
gstreamer1-plugins-bad-free-1.20.3-1.fc36.x86_64
gstreamer1-plugins-bad-freeworld-1.20.3-1.fc36.x86_64
gstreamer1-plugins-bad-freeworld-1.20.3-1.fc36.i686
gstreamer1-plugins-bad-free-1.20.3-1.fc36.i686

**Comment by fzwoch** [comment]
`$ gst-inspect-1.0 vapostproc` would be the easiest check.

**Comment by GloriousEggroll** [comment]
$ gst-inspect-1.0 vapostproc
No such element or plugin 'vapostproc'

seems its missing, guess I need to dig around and find what the fedora package is for it

**Comment by GloriousEggroll** [comment]
yep, all good now. closing
