### ISSUE TITLE
AV1 encoder

### ISSUE THREAD

**Issue by fzwoch** [fzwoch/obs-vaapi#6]
AV1 support requires up-stream merge of the AV1 encoder element:

https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/3015

Currently scheduled for GStreamer 1.24 inclusion.

**Comment by fzwoch** [comment]
Has been merged to main for the 1.24 dev cycle.

**Comment by 32bitx64bit** [comment]
Hey, anyone looking to use Av1, the AUR has a OBS package called "OBS-Studio-av1"
https://aur.archlinux.org/packages/obs-studio-av1

so if you want to use OBS Av1, heres your best shot till 1.24 comes out.
Hopefully it'll be soon. But in the mean time, this'll have to do.

**Comment by 32bitx64bit** [comment]
Yo, I don't really know much about their release cycle, but after lookin into the commits, it seems gstreamer 1.23.90 has Av1 capability included.
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/commit/d474de8ff0d188fb5b0374f6fa2ad21df05ee5e3

**Comment by fzwoch** [comment]
They do. Maybe not inuitive to outsiders. Stable releases are even major number. On the way to stable they have odd major numbers. Beta starts from lower minor numbers (e.g. 0, 1, 2 ..) and release candidates start from 90 (91, 92, 93..).
But that means next stable is very close.

**Comment by fzwoch** [comment]
GStreamer 1.24 is out.

Closing this issue, if there is a problem with this plugin working with it open a new ticket.
