### ISSUE TITLE
Publish to flathub

### ISSUE THREAD

**Issue by RushingAlien** [fzwoch/obs-vaapi#8]
Hello! I have packaged your project as a flatpak over at https://github.com/RushingAlien/com.obsproject.Studio.Plugin.Vaapi, however before i can start publishing this to flathub, I need your consent. So with this in mind, I ask for your consent regarding publishing the project to flathub. Many thanks.

**Comment by fzwoch** [comment]
Well, of course! :+1:

**Comment by RushingAlien** [comment]
https://github.com/flathub/com.obsproject.Studio.Plugin.GStreamerVaapi

It's now merged :partying_face:
